### ISSUE TITLE
CFC to migrate to the CSSWG

### ISSUE THREAD

**Issue by RByers** [WICG/ScrollAnchoring#10]
CSS WG just [discussed](https://github.com/css-meeting-bot) this feature and resolved that they'd be interested in adopting the spec if the editors are OK with that.

@skobes would that be OK with you?  They understand that you will not be attending CSS WG calls or meetings and that all work will continue to happen in GitHub.  I guess we should remove Yash as an editor since he doesn't work on web platform stuff anymore?  @tabatkins said he's willing to be added as an additional editor if desired.

@cwilso what else is required from a process perspective?

**Comment by RByers** [comment]
In particular there's some meta information here in this repo (commit history, Explainer, README, issue history, etc.) that would be nice to preserve.  Perhaps we can migrate the spec while leaving the repo for historical purposes with a forwarding link (similar to [EventListenerOptions](https://github.com/WICG/EventListenerOptions))?

**Comment by skobes-chromium** [comment]
Sounds good to me. I'll add Tab as co-editor and drop Yash.

**Comment by marcoscaceres** [comment]
Hi, @tabatkins pinged me saying that you would like to migrate. 

Can you please fill out one of these: 
 https://wicg.github.io/admin/intent-to-migrate.html

Maybe drop it here first, we can have a quick review of it, then send it off the the CSS WG.

**Comment by yoavweiss** [comment]
After the intent, you'd need to ping @sideshowbarker as he has admin privileges on both orgs and therefore can move repos from one to the other.

**Comment by tabatkins** [comment]
I said this over in the Gitter: 

>  This form appears to be meant for people migrating things to the WICG. The "Proposal" section talks explicitly about this (referring to you having a 'basic proposal' hopefully in a GH repo), and many of the other sections are a pretty basic "early evaluation" sort of thing.
>
> I also, uh, already explained all of this to the CSSWG, and we have an official group resolution to take it on as a CSSWG product (detailed at my previous link). Unsure why I need to repeat this for the CSSWG to see again.

**Comment by marcoscaceres** [comment]
Hi Tab, sorry if the wording is not correct on the Intent to Migrate (I'll try to fix it). It's definitely for migration "out of" - not "in to" - the WICG. See also the steps listed here: https://github.com/WICG/admin/blob/gh-pages/README.md

The intent to migrate serves as a public record, because of IPR. It also signals that work at the WICG on that spec is formally stopping. 

Anyway, if the spec and WG already said it's fine to take it - then I don't think there is any issue with you just moving the repo - specially if whoever worked on the spec is ok with that.

**Comment by marcoscaceres** [comment]
@skobes will you continue to edit this spec? If so, do you work for a W3C member company or will you need to become an Invited Expert?

**Comment by tabatkins** [comment]
@skobes is a Googler, I'm coming on as a co-editor and will be handling spec duties within the CSSWG.

**Comment by marcoscaceres** [comment]
Too easy then 🤙 Super excited to see this progress.

**Comment by tabatkins** [comment]
All right, spec converted to Bikeshed and [moved to the CSSWG](https://drafts.csswg.org/css-scroll-anchoring/), and the existing spec is tombstoned, with links to the new location in the spec, the explainer, and the readme.

**Comment by RByers** [comment]
Excellent, thank you Tab!
