### ISSUE TITLE
Upstream blink tests to the W3C

### ISSUE THREAD

**Issue by RByers** [WICG/ScrollAnchoring#3]
If we get support from other implementors for [moving this proposal to the WICG](https://discourse.wicg.io/t/proposal-scroll-anchoring/1752) then we should upstream the [tests in blink](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/layout/scroll-anchoring/?q=scroll-anchoring&sq=package:chromium&dr) to [web-platform-tests](https://github.com/w3c/web-platform-tests)

**Comment by skobes-chromium** [comment]
Agreed.  Also note additional test cases in [ScrollAnchorTest](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/layout/ScrollAnchorTest.cpp).

**Comment by skobes-chromium** [comment]
This is finished: https://github.com/w3c/web-platform-tests/tree/master/scroll-anchoring
