### ISSUE TITLE
Does scroll anchoring trigger a scroll event?

### ISSUE THREAD

**Issue by stuartpb** [WICG/ScrollAnchoring#5]
The spec right now doesn't mention the scroll position adjustments made by Scroll Anchoring producing any feedback. I think this should trigger a `scroll` event (or a new superset event like `scrollupdate`) with something like an `anchored: true` flag (and/or another property for `scroll` events like `update` that denotes that the change was made by the user-agent in the service of *preserving* the user's current position, rather than the user scrolling to *change* it - one that could also be surfaced, say, when restoring scroll position after navigation), so that code that uses scroll position for something that wouldn't trigger a suppression trigger (like, if I'm reading this right, repositioning an absolutely-positioned element that is a *sibling / cousin* of the scroll anchor in a fixed-like style) doesn't break because it's expecting to get a `scroll` event any time `scrollTop` / `scrollLeft` would change.

**Comment by skobes-chromium** [comment]
Scroll anchoring triggers a scroll event just like other kinds of scrolling.  The spec should probably mention this, thanks for pointing it out.

The scroll event does not currently distinguish different kinds of triggers (anchoring, user scrolls, Javascript scrolls, etc).  Note that anchoring is not the only case of scrolling done by the user-agent - for example, if the content shrinks we may scroll to stay <= the max offset.

I can see how it might be useful to have this kind of information in the scroll event, but it would take some effort to design a good API for that.  One complicating factor is that scroll events are coalesced, so they may reflect more than one "trigger".

**Comment by skobes-chromium** [comment]
I've updated [section 2.2](https://skobes.github.io/ScrollAnchoring/#scroll-adjustment) to clarify that scroll events are generated.
