### ISSUE TITLE
Odd wording around opt-out and other conditions

### ISSUE THREAD

**Issue by j9t** [WICG/ScrollAnchoring#8]
“under the W3C Community Contributor License Agreement (CLA) there is a limited opt-out and other conditions apply” sounds funny (though my ears are foreign). Could something like “under the W3C Community Contributor License Agreement (CLA) there is a limited opt-out. Other conditions may apply.” read better?

**Comment by skobes-chromium** [comment]
@tabatkins, it looks like this wording is added automatically by ReSpec, do you know how to change it?

**Comment by tabatkins** [comment]
Nope, I have zero control over or knowledge of ReSpec. Switch the spec to Bikeshed. (Or I'll do it for you sometime soon.)

**Comment by skobes-chromium** [comment]
Duping into https://github.com/WICG/ScrollAnchoring/issues/12
